#!/bin/bash
# Blocate v1.1 - MPL - John Boero - boeroboy@gmail.com
export BLOCATEPARA=${BLOCATEPARA:-10}
export COMPARE=LIKE

function findpath()
{
	local a
	local r=$(sqlite3 -readonly "$BINDEXDB" \
		"select id, parent, name from inode_v1 where id = $1;")
	if [[ -z "$r" ]]; then
		return
	fi
	IFS='|' read -r -a a <<< "$r"
	findpath "${a[1]}"
	echo -n "/${a[2]}"
}

while getopts ":rh" opt; do
  case ${opt} in
    r ) export COMPARE=REGEXP ;;
    h ) echo "Usage: blocate [-r regex] search [./blocate.sqlite]" ; exit ;;
  esac
  shift $((OPTIND -1))
done

export SEARCH=$(echo $1 | sed "s/'/''/g")
export BINDEXDB="${BINDEXDB:-${2:-blocate.sqlite}}"
export -f findpath
sqlite3 -readonly "$BINDEXDB" "select id from inode_v1 where name $COMPARE '$SEARCH';" | \
	parallel --max-procs=$BLOCATEPARA 'findpath {} ; echo'
